---
title: "draft"
author: "Tiara Dwiputri"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
kec <- housing %>% 
  group_by(kecamatan) %>% 
  summarise(harga = mean(harga))

idn3@data <- idn3@data %>% 
  left_join(kec, by = c("NAME_3" = "kecamatan"))
```

```{r}
idn3@data$NAME_1 %>% unique
```


```{r}
library(tmap)
jawa <- c("Banten", "Jawa Barat","Jakarta Raya")
qtm(idn3[idn3$NAME_1 %in% jawa,], 'harga')
```


```{r}
library(dplyr)
jawa <- c("Banten", "Jawa Barat", "Jawa Tengah", "Jawa Timur", "Jakarta Raya", "Yogyakarta")
plot(indo, col='white')
plot(indo[indo$NAME_1 %in% jawa,], col='tomato3', add=TRUE)
  
```

```{r}
summary(indo)
```

```{r}
library(tmap)
qtm(idn3, 'VARNAME_1')
```

```{r}
bbox(indo)
```


```{r}
library(ggplot2)
```

```{r}
indo_f <- fortify(indo)

indo$id <- row.names(indo) 
indo_f <- left_join(indo_f, indo@data)
ggplot(indo_f, aes(long,lat, group = group, fill=VARNAME_1)) +
  geom_polygon() + coord_equal() +
  labs(fill = "Random Number") +
  ggtitle("Indonesia Random Number") +
  scale_fill_gradient(low = "white", high = "tomato3")

```